### ISSUE TITLE
hypertag does not capture <custom-elements>

### ISSUE THREAD

**Issue by blynx** [AndreasPizsa/hypertag#1]
Hi,

hypertag does not capture Custom Elements properly. I think a simple extension to the regex might fix it: `/(\w+)...` to something like `/([\w-]+)...` to include dashed tag names.

Cheers
Steffen

**Comment by andreaspitzer** [comment]
Great find @blynx , thanks for opening the issue.

Fixed it and published a new version, please give it a try!

Best,
Andreas
